{
 "title": "Fastly Service",
 "tags": [ "Fastly" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(fastly_rt_requests_total, service_name)"
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": "label_values(fastly_rt_requests_total, service_id)"
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": "label_values(fastly_rt_requests_total, datacenter)"
   },
   {
    "name": "rate",
    "label": "Rate",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "HEALTH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "2XX",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_status_group_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"2xx\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\",}[$rate]))"
    }
   ]
  },
  {
   "title": "3XX",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_status_group_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"3xx\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\",}[$rate]))"
    }
   ]
  },
  {
   "title": "4XX",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_status_group_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"4xx\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\",}[$rate]))"
    }
   ]
  },
  {
   "title": "5XX",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_status_group_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"5xx\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\",}[$rate]))"
    }
   ]
  },
  {
   "title": "FASTLY ERRORS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_errors_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\",}[$rate]))"
    }
   ]
  },
  {
   "title": "REQ HEADER",
   "type": "singlestat",
   "description": "69KB limit per https://docs.fastly.com/en/guides/resource-limits#request-and-header-limits",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_req_header_bytes_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\",}[$rate])) / 69000"
    }
   ]
  },
  {
   "title": "RESP HEADER",
   "type": "singlestat",
   "description": "69KB limit per https://docs.fastly.com/en/guides/resource-limits#request-and-header-limits",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_resp_header_bytes_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\",}[$rate])) / 69000"
    }
   ]
  },
  { "title": "CACHE & SHIELDING", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "HIT RATIO",
   "type": "singlestat",
   "description": "HITS / ( HITS + MISS )",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_hits_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / (sum(rate(fastly_rt_hits_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))\n+ sum(rate(fastly_rt_miss_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])))"
    }
   ]
  },
  {
   "title": "HITS",
   "type": "singlestat",
   "description": "HITS / REQUESTS",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_hits_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))"
    }
   ]
  },
  {
   "title": "MISS",
   "type": "singlestat",
   "description": "MISS / REQUESTS",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_miss_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))\n"
    }
   ]
  },
  {
   "title": "PASS",
   "type": "singlestat",
   "description": "PASS / REQUESTS",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_pass_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))"
    }
   ]
  },
  {
   "title": "SYNTHETIC",
   "type": "singlestat",
   "description": "SYNTHETIC / REQUESTS",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_synth_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))"
    }
   ]
  },
  {
   "title": "SHIELDING",
   "type": "singlestat",
   "description": "SHIELD > 0",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_shield_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))"
    }
   ]
  },
  {
   "title": "TO SHIELD",
   "type": "singlestat",
   "description": "SHIELD / REQUESTS",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_shield_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))"
    }
   ]
  },
  {
   "title": "SHIELDS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_shield_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (datacenter)",
     "legendFormat": "{{datacenter}}"
    }
   ]
  },
  { "title": "SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "BANDWIDTH & REQUESTS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(fastly_rt_body_size_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))",
     "legendFormat": "{{Bandwidth}}"
    },
    {
     "expr": "sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))",
     "legendFormat": "{{Requests}}"
    }
   ]
  },
  {
   "title": "HTTP STATUS CODES",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_status_code_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_code=~\".+\"}[$rate])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP STATUS CODES BREAKDOWN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "2XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_status_code_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_code=~\"2..\"}[$rate])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "3XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_status_code_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_code=~\"3..\"}[$rate])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "4XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_status_code_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_code=~\"4..\"}[$rate])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "5XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_status_code_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_code=~\"5..\"}[$rate])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Average Header Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_req_header_bytes_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\",}[$rate]))",
       "legendFormat": "Request"
      },
      {
       "expr": "sum(rate(fastly_rt_resp_header_bytes_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\",}[$rate]))",
       "legendFormat": "Response"
      }
     ]
    },
    {
     "title": "REQUESTS per DATACENTER",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\",}[$rate])) by (datacenter)",
       "legendFormat": "{{datacenter}}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_errors_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) ",
       "legendFormat": "ERRORS"
      }
     ]
    },
    {
     "title": "5XX per REQUEST by DATACENTER",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_status_group_total{service_name=~\"$service_name\",service_id=~\"$service_id\", status_group=\"5xx\", datacenter=~\"$datacenter\"}[30s])) by (datacenter) / sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\",}[$rate])) by (datacenter)",
       "legendFormat": "{{datacenter}}"
      }
     ]
    }
   ]
  }
 ]
}