{
 "title": "Fastly Top Datacenters",
 "tags": [ "Fastly" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(fastly_rt_requests_total, service_name)"
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": "label_values(fastly_rt_requests_total, service_id)"
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": "label_values(fastly_rt_requests_total, datacenter)"
   },
   {
    "name": "rate",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "top_datacenter_requests_total",
    "query": "query_result(topk(10, max(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (datacenter)))\n"
   },
   {
    "name": "top_datacenter_errors_total",
    "query": "query_result(topk(10, max(rate(fastly_rt_errors_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (datacenter)))\n"
   },
   {
    "name": "top_datacenter_body_size_total",
    "query": "query_result(topk(10, max(rate(fastly_rt_body_size_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (datacenter)))\n"
   },
   {
    "name": "top_datacenter_error_per_request",
    "query": "query_result(topk(10, max(rate(fastly_rt_errors_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (datacenter) / max(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (datacenter)))"
   },
   {
    "name": "top_datacenter_impaired",
    "query": "query_result(topk(10, max(rate(fastly_rt_errors_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (datacenter) / max(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (datacenter) ))"
   },
   {
    "name": "top_datacenter_status_group_total_4xx",
    "query": "query_result(topk(10, max(rate(fastly_rt_status_group_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"4xx\"}[${__range_s}s])) by (datacenter)))\n"
   },
   {
    "name": "top_datacenter_status_group_total_5xx",
    "query": "query_result(topk(10, max(rate(fastly_rt_status_group_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"5xx\"}[${__range_s}s])) by (datacenter)))\n"
   },
   {
    "name": "top_datacenter_4xx_per_request",
    "query": "query_result(topk(10, max(rate(fastly_rt_status_group_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"4xx\"}[${__range_s}s])) by (datacenter) / max(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (datacenter)))\n"
   },
   {
    "name": "top_datacenter_5xx_per_request",
    "query": "query_result(topk(10, max(rate(fastly_rt_status_group_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"5xx\"}[${__range_s}s])) by (datacenter) / max(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (datacenter)))\n"
   },
   {
    "name": "top_datacenter_origin_latency_p99",
    "query": "query_result(topk(10, histogram_quantile(0.99,sum(rate(fastly_rt_miss_duration_seconds_bucket{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (le,datacenter))))"
   }
  ]
 },
 "panels": [
  {
   "title": "ACTIVELY USED DATACENTERS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (datacenter) >0)",
     "legendFormat": "Datacenters"
    }
   ]
  },
  { "title": "SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "REQUESTS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_requests_total{datacenter=~\"$top_datacenter_requests_total\",service_name=~\"$service_name\", service_id=~\"$service_id\"}[$rate])) by (datacenter)",
     "legendFormat": "{{datacenter}}"
    }
   ]
  },
  {
   "title": "BANDWIDTH",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(fastly_rt_body_size_total{datacenter=~\"$top_datacenter_body_size_total\",service_name=~\"$service_name\", service_id=~\"$service_id\"}[$rate])) by (datacenter)",
     "legendFormat": "{{datacenter}}"
    }
   ]
  },
  {
   "title": "ORIGIN LATENCY - P99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(fastly_rt_miss_duration_seconds_bucket{datacenter=~\"$top_datacenter_origin_latency_p99\",service_name=~\"$service_name\", service_id=~\"$service_id\"}[$rate])) by (le,datacenter))",
     "legendFormat": "{{datacenter}}"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_errors_total{datacenter=~\"$top_datacenter_errors_total\",service_name=~\"$service_name\", service_id=~\"$service_id\"}[$rate])) by (datacenter)",
     "legendFormat": "{{datacenter}}"
    }
   ]
  },
  {
   "title": "4XX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_status_group_total{datacenter=~\"$top_datacenter_status_group_total_4xx\", status_group=~\"4xx\",service_name=~\"$service_name\", service_id=~\"$service_id\"}[$rate])) by (datacenter,status_code)",
     "legendFormat": "{{datacenter}}"
    }
   ]
  },
  {
   "title": "5XX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_status_group_total{datacenter=~\"$top_datacenter_status_group_total_5xx\", status_group=~\"5xx\",service_name=~\"$service_name\", service_id=~\"$service_id\"}[$rate])) by (datacenter, status_code)",
     "legendFormat": "{{datacenter}} "
    }
   ]
  },
  {
   "title": "MISC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "4XX IMPAIRED",
     "type": "graph",
     "description": "4XX per REQUESTS by 4XX",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_status_group_total{datacenter=~\"$top_datacenter_4xx_per_request\", status_group=~\"4xx\",service_name=~\"$service_name\", service_id=~\"$service_id\"}[$rate])) by (datacenter,status_code)",
       "legendFormat": "{{datacenter}}"
      }
     ]
    },
    {
     "title": "5XX IMPAIRED",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_status_group_total{datacenter=~\"$top_datacenter_5xx_per_request\", status_group=~\"5xx\",service_name=~\"$service_name\", service_id=~\"$service_id\"}[$rate])) by (datacenter,status_code)",
       "legendFormat": "{{datacenter}}"
      }
     ]
    },
    {
     "title": "4XX per REQUEST",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_status_group_total{datacenter=~\"$top_datacenter_4xx_per_request\", status_group=\"4xx\",service_name=~\"$service_name\", service_id=~\"$service_id\"}[$rate])) by (datacenter) / sum(rate(fastly_rt_requests_total{datacenter=~\"$top_datacenter_4xx_per_request\",service_name=~\"$service_name\", service_id=~\"$service_id\"}[$rate])) by (datacenter)",
       "legendFormat": "{{datacenter}}"
      }
     ]
    },
    {
     "title": "5XX per REQUEST",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_status_group_total{datacenter=~\"$top_datacenter_5xx_per_request\", status_group=\"5xx\",service_name=~\"$service_name\", service_id=~\"$service_id\"}[$rate])) by (datacenter) / sum(rate(fastly_rt_requests_total{datacenter=~\"$top_datacenter_5xx_per_request\",service_name=~\"$service_name\", service_id=~\"$service_id\"}[$rate])) by (datacenter)",
       "legendFormat": "{{datacenter}}"
      }
     ]
    },
    {
     "title": "DEAD ",
     "type": "graph",
     "description": "ERRORS >= REQUESTS, by ERRORS",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_errors_total{datacenter=~\"$top_datacenter_error_per_request\",service_name=~\"$service_name\", service_id=~\"$service_id\"}[$rate])) by (datacenter) \n",
       "legendFormat": "{{datacenter}}"
      }
     ]
    },
    {
     "title": "IMPAIRED",
     "type": "graph",
     "description": "REQUESTS > ERRORS, by ERRORS / REQUESTS",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_errors_total{datacenter=~\"$top_datacenter_impaired\",service_name=~\"$service_name\", service_id=~\"$service_id\"}[$rate])) by (datacenter) ",
       "legendFormat": "{{datacenter}}"
      }
     ]
    }
   ]
  }
 ]
}