{
 "title": "Fastly Top Services",
 "tags": [ "Fastly" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(fastly_rt_requests_total, service_name)"
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": "label_values(fastly_rt_requests_total, service_id)"
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": "label_values(fastly_rt_requests_total, datacenter)"
   },
   {
    "name": "rate",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "top_service_id_requests_total",
    "query": "query_result(topk(10, max(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (service_id)))\n"
   },
   {
    "name": "top_service_id_errors_total",
    "query": "query_result(topk(10, max(rate(fastly_rt_errors_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (service_id)))\n"
   },
   {
    "name": "top_service_id_body_size_total",
    "query": "query_result(topk(10, max(rate(fastly_rt_body_size_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (service_id)))\n"
   },
   {
    "name": "top_service_id_error_per_request",
    "query": "query_result(topk(10, max(rate(fastly_rt_errors_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (service_id) / max(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (service_id)))"
   },
   {
    "name": "top_service_id_impaired",
    "query": "query_result(topk(10, max(rate(fastly_rt_errors_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (service_id) / max(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (service_id) ))"
   },
   {
    "name": "top_service_id_status_group_total_4xx",
    "query": "query_result(topk(10, max(rate(fastly_rt_status_group_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"4xx\"}[${__range_s}s])) by (service_id)))\n"
   },
   {
    "name": "top_service_id_status_group_total_5xx",
    "query": "query_result(topk(10, max(rate(fastly_rt_status_group_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"5xx\"}[${__range_s}s])) by (service_id)))\n"
   },
   {
    "name": "top_service_id_4xx_per_request",
    "query": "query_result(topk(10, max(rate(fastly_rt_status_group_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"4xx\"}[${__range_s}s])) by (service_id) / max(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (service_id)))\n"
   },
   {
    "name": "top_service_id_5xx_per_request",
    "query": "query_result(topk(10, max(rate(fastly_rt_status_group_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"5xx\"}[${__range_s}s])) by (service_id) / max(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (service_id)))\n"
   },
   {
    "name": "top_service_id_origin_latency_p99",
    "query": "query_result(topk(10, histogram_quantile(0.99,sum(rate(fastly_rt_miss_duration_seconds_bucket{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (le,service_id))))"
   }
  ]
 },
 "panels": [
  { "title": "SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "REQUESTS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_requests_total{service_id=~\"$top_service_id_requests_total\", service_name=~\".*\"}[$rate])) by (service_id,service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "BANDWIDTH",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(fastly_rt_body_size_total{service_id=~\"$top_service_id_body_size_total\", service_name=~\".*\"}[$rate])) by (service_id,service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "ORIGIN LATENCY - P99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(fastly_rt_miss_duration_seconds_bucket{service_name=~\".+\", service_id=~\"$top_service_id_origin_latency_p99\", datacenter=~\".+\"}[$rate])) by (le,service_name))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_errors_total{service_id=~\"$top_service_id_errors_total\", service_name=~\".*\"}[$rate])) by (service_id,service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "4XX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_status_group_total{service_id=~\"$top_service_id_status_group_total_4xx\", status_group=~\"4xx\", service_name=~\".+\"}[$rate])) by (service_id,service_name,status_code)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "5XX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_status_group_total{service_id=~\"$top_service_id_status_group_total_5xx\", status_group=~\"5xx\", service_name=~\".+\"}[$rate])) by (service_id,service_name, status_code)",
     "legendFormat": "{{service_name}} "
    }
   ]
  },
  {
   "title": "MISC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "4XX IMPAIRED",
     "type": "graph",
     "description": "4XX per REQUESTS by 4XX",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_status_group_total{service_id=~\"$top_service_id_4xx_per_request\", status_group=~\"4xx\", service_name=~\".+\"}[$rate])) by (service_id,service_name,status_code)",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "5XX IMPAIRED",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_status_group_total{service_id=~\"$top_service_id_5xx_per_request\", status_group=~\"5xx\", service_name=~\".+\"}[$rate])) by (service_id,service_name,status_code)",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "4XX per REQUEST",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_status_group_total{service_name=~\".+\",service_id=~\"$top_service_id_4xx_per_request\", status_group=\"4xx\"}[$rate])) by (service_name,service_id) / sum(rate(fastly_rt_requests_total{service_name=~\".+\",service_id=~\"$top_service_id_4xx_per_request\"}[$rate])) by (service_name,service_id)",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "5XX per REQUEST",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_status_group_total{service_name=~\".+\",service_id=~\"$top_service_id_5xx_per_request\", status_group=\"5xx\"}[$rate])) by (service_name,service_id) / sum(rate(fastly_rt_requests_total{service_name=~\".+\",service_id=~\"$top_service_id_5xx_per_request\"}[$rate])) by (service_name,service_id)",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "DEAD ",
     "type": "graph",
     "description": "ERRORS >= REQUESTS, by ERRORS",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_errors_total{service_name=~\".*\", service_id=~\"$top_service_id_error_per_request\"}[$rate])) by (service_name, service_id) \n",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "IMPAIRED",
     "type": "graph",
     "description": "REQUESTS > ERRORS, by ERRORS / REQUESTS",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_rt_errors_total{service_name=~\".*\", service_id=~\"$top_service_id_impaired\"}[$rate])) by (service_id, service_name) ",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  }
 ]
}